{
 "title": "Blackbox Exporter",
 "description": "Prometheus Blackbox Exporter Overview",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success, target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{target=~\"$target\"} - 0  "
    },
    {
     "expr": "probe_http_ssl{target=~\"$target\"} - 0"
    },
    {
     "expr": "probe_http_status_code{target=~\"$target\"} - 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{target=~\"$target\"}-time()"
    }
   ]
  },
  {
   "title": "Global Probe Duration",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$target\"}",
     "legendFormat": "{{ target }}"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "target" },
  {
   "title": "Status",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{target=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{target=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{target=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_status_code{target=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_version{target=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_http_ssl{target=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 2, "w": 10, "x": 4, "y": 30 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{target=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 30 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{target=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 30 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{target=~\"$target\"})"
    }
   ]
  }
 ]
}