{
 "title": "Metallb",
 "description": "Metallb key metrics",
 "tags": [
  "metallb ",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Address utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metallb_allocator_addresses_total",
     "legendFormat": "available"
    },
    {
     "expr": "metallb_allocator_addresses_in_use_total",
     "legendFormat": "in use"
    }
   ]
  },
  {
   "title": "Stale config",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(metallb_k8s_client_config_stale_bool)",
     "legendFormat": "client_config_stale"
    }
   ]
  },
  {
   "title": "Client updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(metallb_k8s_client_update_errors_total[5m])",
     "legendFormat": "{{container}} errors"
    },
    {
     "expr": "rate(metallb_k8s_client_updates_total[5m])",
     "legendFormat": "{{container}} updates"
    }
   ]
  }
 ]
}