{
 "title": "NUT",
 "description": "Example dashboard for HON95's Prometheus NUT Exporter.",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ups", "label": "UPS", "query": { "query": "nut_ups_info" } },
   { "name": "smoothing_interval", "label": "Smoothing", "query": "1m,5m,15m,1h,1d,1w" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_status{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_input_voltage_volts{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_load{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_battery_runtime_seconds{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Beeper Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_beeper_status{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Charge [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * avg_over_time(nut_battery_charge{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Runtime [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(nut_battery_runtime_seconds{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(nut_load{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Voltage [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(nut_battery_voltage_volts{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Voltage [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(nut_input_voltage_volts{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Output Voltage [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(nut_output_voltage_volts{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  }
 ]
}