{
 "title": "S.M.A.R.T Errors",
 "description": "Smartmon Texfile node_exporter",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(smartmon_smartctl_version, instance)"
    }
   },
   {
    "name": "device_model",
    "query": {
     "query": "label_values(smartmon_device_info, device_model)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(smartmon_device_info, disk)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Read_Error_Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_raw_read_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\" }",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Reallocate_Events",
   "type": "gauge",
   "description": "Number of reallocation events.\nCaused by read errors and broken sectors.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_reallocated_event_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Pending_Sectors",
   "type": "gauge",
   "description": "Number of unstable sectors.\nCaused by read errors. \nWill possibly be remapped.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_current_pending_sector_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Offline_Uncorrectable_Sectors",
   "type": "gauge",
   "description": "Number of uncorrectable sectors.\nDetected by a self-test (called offline scan)",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_offline_uncorrectable_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "UDMA_CRC_Errors",
   "type": "gauge",
   "description": "Monitors connection quality between disk and motherboard.\nIndicates bad cable connection/cables.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_udma_crc_error_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  { "title": "HDD Specific Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Seek_Error_Rate",
   "type": "gauge",
   "description": "Errors during read action.\nPossible positioning problem of  read/write unit",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_seek_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\" }",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Multi_Zone_Error_Rate",
   "type": "gauge",
   "description": "Errors during write",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_multi_zone_error_rate_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Spin_Retry_Count",
   "type": "gauge",
   "description": "Cont unsuccessful attempts to spin up to operational speed. \nCritical value indicating a mechanical problem of the motor.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_spin_retry_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  }
 ]
}