{
 "title": "S.M.A.R.T Monitoring",
 "description": "Smartmon Texfile node_exporter Dashboard",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(smartmon_smartctl_version, instance)"
    }
   },
   {
    "name": "device_model",
    "query": {
     "query": "label_values(smartmon_device_info, device_model)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(smartmon_device_info, disk)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unhealthy Disks",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(smartmon_device_smart_healthy{instance=~\"$instance\"})-sum(smartmon_device_smart_healthy{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum( smartmon_reallocate_nand_blk_cnt_raw_value ) +\nsum( smartmon_reallocated_sector_ct_raw_value ) +\nsum( smartmon_reallocated_event_count_raw_value ) +\nsum( smartmon_raw_read_error_rate_raw_value ) +\nsum( smartmon_current_pending_sector_raw_value ) +\nsum( smartmon_offline_uncorrectable_raw_value ) +\nsum( smartmon_udma_crc_error_count_raw_value ) +\nsum( smartmon_seek_error_rate_raw_value ) +\nsum( smartmon_spin_retry_count_raw_value ) +\nsum( smartmon_multi_zone_error_rate_raw_value )"
    }
   ]
  },
  {
   "title": "Active devices",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(smartmon_device_active)" }
   ]
  },
  {
   "title": "Temperature_Graph",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(smartmon_temperature_celsius_raw_value{ instance=~\"$instance\", disk=~\"$disk\" }) by (instance, disk)",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Temperture_Gauge",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_temperature_celsius_raw_value{ instance=~\"$instance\", disk=~\"$disk\" }",
     "legendFormat": "{{ disk }}"
    }
   ]
  },
  {
   "title": "Device_Info",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 11 },
   "targets": [
    { "expr": "smartmon_device_info" }
   ]
  },
  {
   "title": "Power_On_Hours",
   "type": "bargauge",
   "description": "yellow after 1 year\nred after 1 1/2 years",
   "gridPos": { "h": 14, "w": 8, "x": 7, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_power_on_hours_raw_value{ disk=~\"$disk\", instance=~\"$instance\" }",
     "legendFormat": " {{disk}}"
    }
   ]
  },
  {
   "title": "Power_Cycle_Count",
   "type": "gauge",
   "description": "Number of times disk was turned on",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_power_cycle_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  { "title": "Specific Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "SSD Remaining_Lifetime",
   "type": "bargauge",
   "description": "Estimated remaining lifetime.\nBased on amount of written data.\n(Very vague one flash chip can be witten 10 000 times)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_percent_lifetime_remain_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "Spin_Up_Time",
   "type": "bargauge",
   "description": "Average time to spin up disk. (in ms)\nHigh values indicate problems with the motor.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_spin_up_time_raw_value",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "HDD Power_Off_Retract_Count",
   "type": "gauge",
   "description": "Number of unexpected power outages (no correct shutdown) \nThis kind of shutdown lowers the lifetime of a disk way more than a clean shutdown",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_power_off_retract_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "HDD Start_Stop_Count",
   "type": "gauge",
   "description": "Counts start/stop events.\nHigh values indicate high wear.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_start_stop_count_raw_value { instance=~\"$instance\", disk=~\"$disk\" }",
     "legendFormat": "{{disk}}"
    }
   ]
  },
  {
   "title": "HDD Load_Cycle_Count",
   "type": "gauge",
   "description": "Number times the head was placed in the parking area.\nMostly mobile disks.\n300000 times is intended.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_load_cycle_count_raw_value{ instance=~\"$instance\", disk=~\"$disk\"}",
     "legendFormat": "{{disk}}"
    }
   ]
  }
 ]
}